[package]
name = "tic-tac-toe-cli"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "tic_tac_toe"
path = "src/main.rs"

[dependencies]
tic-tac-toe-logic = { path = "../tic-tac-toe-logic" }
text_io = "0.1.7"
