[package]
name = "pos-install"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../types", package = "casperlabs-types" }
pos = { path = "../pos", default-features = false, features = ["lib"] }
client-api-proxy = { path = "../client-api-proxy", default-features = false, features = ["lib"] }
