[package]
name = "erc20-smart-contract"
version = "0.1.0"
authors = ["Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
doctest = false
test = false

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
erc20_logic  = { path = "../erc20-logic", package = "erc20-logic", default-features = false }
types = { path = "../../../types", package = "casperlabs-types" }
