[package]
name = "casperlabs-proof-of-stake"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[features]
std = []

[dependencies]
types = { path = "../types", package = "casperlabs-types" }
