[package]
name = "tic-tac-toe-smart-contract"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>", "Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
doctest = false
bench = false

[dependencies]
tic-tac-toe-logic = { path = "../tic-tac-toe-logic" }
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../types", package = "casperlabs-types" }
num-traits = { version = "0.2.8", default-features = false }

[dev-dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract", default-features = false, features=["std"] }
